### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by oskarrough** [titoBouzout/FindExcludePatterns#1]
Hi, I've probably missed something but I can't find this package through Package Control neither is it on the browse page and you suggest not to install it manually. So… How to?

And thank you for this, looks like just the plugin I need to save my old laptop!

**Comment by stevebeck** [comment]
+1

**Comment by kyle-sama** [comment]
+1

**Comment by ozalexo** [comment]
Hi. Any news about installation via Package Manager?

**Comment by titoBouzout** [comment]
I merge this package into this other https://github.com/titoBouzout/FindResultsApplyChanges
